### ISSUE TITLE
dev test net platon_mtool report error when do staking

### ISSUE THREAD

**Issue by junjiequ123** [PlatONnetwork/mtool#4]
background : dev net mtool download page returns 404, using mainet mtool instead
---------------
alaya@sgp-demo-001:~$ platon_mtool --version
version: 1.0.1
timestamp: 2021-08-05 15:28:51
revision: b008e7ed4f107c5a27b3a9609951f47023f81487
sdk version: 0.15.1.15-SNAPSHOT
-----------------------
alaya@sgp-demo-001:~$ platon version
PlatON
Version: 1.0.0-unstable
Git Commit: 62b9a9001794b3d317ead9bd088bd35b1c929dcf
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.13.4
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.13

--------------- error output ----------------
>platon_mtool staking --config $PLATON_MTOOLDIR/validator/validator_config.json --keystore $PLATON_MTOOLDIR/keystore/staking.json --auto
amount 100000 --benefit_address lat1..................................

please input keystore password:
com.platon.contracts.ppos.exception.EstimateGasException: The program version is too low
        at com.platon.contracts.ppos.BaseContract.getDefaultGasProviderRemote(BaseContract.java:229)
        at com.platon.contracts.ppos.BaseContract.getDefaultGasProvider(BaseContract.java:215)
        at com.platon.contracts.ppos.StakingContract.getStakingGasProvider(StakingContract.java:150)
        at com.platon.mtool.client.execute.StakingExecutor.execute(StakingExecutor.java:80)
        at com.platon.mtool.client.execute.StakingExecutor.execute(StakingExecutor.java:29)
        at com.platon.mtool.client.CliExecutor.execute(CliExecutor.java:40)
        at com.platon.mtool.client.MtoolClient.run(MtoolClient.java:334)
        at com.platon.mtool.client.MtoolClient.run(MtoolClient.java:123)
        at com.platon.mtool.client.MtoolClient.main(MtoolClient.java:67)

**Comment by chenxiaodai** [comment]
1. 缺失的下载链接已经更新，目前可以下载了。
2. 报的版本错误问题，需要使用1.0.0底层版本，待块高同步上去后，替换1.1.0底层版本， 最后在质押。 因为历史原因需要这么操作。 后面开发网会重新部署。

**Comment by junjiequ123** [comment]
before try : sudo wget https://download.platon.network/platon/platon/1.1.0/platon -O /usr/bin/platon
tested below, and got 404..... means, I need to build 1.1.0 by myself?

alaya@sgp-demo-001:~/download$ sudo wget https://download.platon.network/platon/1.1.0/platon -O ~/download/platon
--2021-08-29 11:04:10--  https://download.platon.network/platon/1.1.0/platon
Resolving download.platon.network (download.platon.network)... 8.210.172.135
Connecting to download.platon.network (download.platon.network)|8.210.172.135|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-08-29 11:04:10 ERROR 404: Not Found.

**Comment by junjiequ123** [comment]
guess the new URL is ......  works

alaya@sgp-demo-001:~/download$ sudo wget https://download.platon.network/platon/devnet/platon/1.1.0/platon -O ~/downlo
ad/platon
--2021-08-29 11:09:58--  https://download.platon.network/platon/devnet/platon/1.1.0/platon
Resolving download.platon.network (download.platon.network)... 8.210.172.135
Connecting to download.platon.network (download.platon.network)|8.210.172.135|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 40309016 (38M) [application/octet-stream]
Saving to: ‘/home/alaya/download/platon’

/home/alaya/download/platon   100%[===============================================>]  38.44M  11.3MB/s    in 3.4s

2021-08-29 11:10:01 (11.3 MB/s) - ‘/home/alaya/download/platon’ saved [40309016/40309016]

**Comment by chenxiaodai** [comment]
开发网络接入和正式网络接入在文档及安装包下载路径是存在区别的。 可参考 https://devdocs.platon.network/docs/zh-CN/Become_PlatON_Dev_Verification。 下载链接 https://download.platon.network/platon/devnet/platon/1.1.0/platon 是可使用的。

**Comment by junjiequ123** [comment]
works now. leave a comment here
for developers please do check
1. dev net chainId, verify genesis.json defination
2. update chainId in mtool config.properties
 ----- here is what I got at last ----
alaya@sgp-demo-001:~/download/platon_mtool$ diff config.properties config.properties.bad.20210830
1,2c1
< #chainId=201030
< chainId=210309
---
> chainId=201030

**Comment by chenxiaodai** [comment]
十分感谢。 只是mtool中链id需要手工指定，和正式网是相同的安装包。  只是文档描述修改链id的位置不是很清晰。
https://devdocs.platon.network/docs/zh-CN/Become_PlatON_Dev_Verification#%E5%BC%80%E5%8F%91%E7%BD%91%E7%BB%9C%E7%9B%B8%E5%85%B3%E8%B5%84%E6%BA%90

**Comment by zhouxi-jzheng** [comment]
在开发者文档：成为开发网验证节点增加提示，让用户在开发网运行mtool时，记得修改config.properties中的链ID为：210309
https://devdocs.platon.network/docs/zh-CN/Become_PlatON_Dev_Verification#%E4%BF%AE%E6%94%B9configproperties
